### PR TITLE
Added support for providing host_uri argument when creating a Nebula object

### PR DESCRIPTION
**Pull request by vineyyadav**
Associated to https://github.com/nebula-orchestrator/worker/issues/145

Fixes #

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by naorlivne — CHANGES_REQUESTED** [review]
The commit itself looks good but it's lowering the test coverage, can you add a basic test that ensures that if the host_uri is added it's returned as `self.host` ?

**Comment by vineyyadav** [comment]
> 
> 
> The commit itself looks good but it's lowering the test coverage, can you add a basic test that ensures that if the host_uri is added it's returned as `self.host` ?

Done.

**Comment by naorlivne** [comment]
LGTM

**Comment by naorlivne** [comment]
Also feel free add yourself to the contributors file

**Pull request merged**
